nname: Cypress Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Log in to Docker if required
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Docker image and start services
      - name: Build and start Docker services
        run: docker-compose up -d --build

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:3000

      # Archive test results
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results

      # Publish test results
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress
          path: cypress/results/*.json 
          reporter: mochawesome # Adjust based on your reporter
