name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: secret
        env:
          CREDENTIALS: ${{ secrets.CYPRESS_ENV }}
        run: echo $CREDENTIALS > cypress.env.json
        
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install project dependencies
        run: npm install

      - name: Run Cypress Cucumber tests
        run: npx cypress run