name: Cypress Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: secret
        env:
          CREDENTIALS: ${{ secrets.CYPRESS_ENV }}
        run: echo $CREDENTIALS > cypress.env.json

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2 libasound2-dev libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libgconf-2-4
      
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 -ac &

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npm install cypress@13.2.0

      - name: Run Cypress tests
        run: npx cypress run --browser electron --headless --no-sandbox
        env:
          CI: true
          DEBUG: cypress:*

      - name: Upload Cypress report artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos